"""
Canonical Architecture domain model.

Represents the complete system design and technical architecture for a project.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Architecture:
    """
    Canonical Architecture representation for the project.

    Contains system overview, module list, file structures, API/DB design, tech stack,
    and various strategy lists.
    """

    system_overview: str
    modules: list[str] = field(default_factory=list)
    folder_structure: list[str] = field(default_factory=list)
    api_design: list[str] = field(default_factory=list)
    database_design: list[str] = field(default_factory=list)
    technology_stack: dict[str, str] = field(default_factory=dict)
    external_services: list[str] = field(default_factory=list)
    security_considerations: list[str] = field(default_factory=list)
    deployment_strategy: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    future_extensions: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Convert to a JSON-serializable dictionary."""
        return {
            "system_overview": self.system_overview,
            "modules": list(self.modules),
            "folder_structure": list(self.folder_structure),
            "api_design": list(self.api_design),
            "database_design": list(self.database_design),
            "technology_stack": dict(self.technology_stack),
            "external_services": list(self.external_services),
            "security_considerations": list(self.security_considerations),
            "deployment_strategy": list(self.deployment_strategy),
            "risks": list(self.risks),
            "future_extensions": list(self.future_extensions),
        }

    def to_markdown(self) -> str:
        """Convert to a formatted Markdown document."""
        lines = []
        lines.append("# System Architecture Design")
        lines.append("")
        lines.append("## System Overview")
        lines.append("")
        lines.append(self.system_overview)
        lines.append("")

        if self.technology_stack:
            lines.append("## Technology Stack")
            lines.append("")
            for layer, tech in self.technology_stack.items():
                lines.append(f"- **{layer.capitalize()}**: {tech}")
            lines.append("")

        if self.modules:
            lines.append("## Modules & Key Components")
            lines.append("")
            for mod in self.modules:
                lines.append(f"- {mod}")
            lines.append("")

        if self.folder_structure:
            lines.append("## Proposed Folder Structure")
            lines.append("")
            lines.append("```")
            lines.extend(self.folder_structure)
            lines.append("```")
            lines.append("")

        if self.api_design:
            lines.append("## API Endpoints Design")
            lines.append("")
            for api in self.api_design:
                lines.append(f"- {api}")
            lines.append("")

        if self.database_design:
            lines.append("## Database Schema Design")
            lines.append("")
            for db in self.database_design:
                lines.append(f"- {db}")
            lines.append("")

        if self.external_services:
            lines.append("## External Services & Integrations")
            lines.append("")
            for svc in self.external_services:
                lines.append(f"- {svc}")
            lines.append("")

        if self.security_considerations:
            lines.append("## Security Considerations")
            lines.append("")
            for sec in self.security_considerations:
                lines.append(f"- {sec}")
            lines.append("")

        if self.deployment_strategy:
            lines.append("## Deployment Strategy")
            lines.append("")
            for dep in self.deployment_strategy:
                lines.append(f"- {dep}")
            lines.append("")

        if self.risks:
            lines.append("## Technical Risks & Mitigations")
            lines.append("")
            for risk in self.risks:
                lines.append(f"- {risk}")
            lines.append("")

        if self.future_extensions:
            lines.append("## Future Scalability & Extensions")
            lines.append("")
            for ext in self.future_extensions:
                lines.append(f"- {ext}")
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by AI Engineering Team — Architecture Generator*")
        lines.append("")

        return "\n".join(lines)
