"""
Canonical PRD (Product Requirements Document) domain model.

Represents a complete product requirements document for a project.
The PRD Generator produces this model from an analyzed Idea and Requirements.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class PRD:
    """
    A complete Product Requirements Document.

    Generated by the PRD Generator stage from an Idea and Requirements.
    """

    # Identity
    project_title: str
    """Title of the project."""

    # Overview
    problem_statement: str = ""
    """The problem this project solves."""

    project_vision: str = ""
    """The long-term vision for the product."""

    target_audience: list[str] = field(default_factory=list)
    """Who the product is for."""

    # Product Details
    user_personas: list[str] = field(default_factory=list)
    """Detailed user personas."""

    user_journeys: list[str] = field(default_factory=list)
    """Key user journeys through the product."""

    features: list[str] = field(default_factory=list)
    """Detailed feature descriptions."""

    # Success Metrics
    success_metrics: list[str] = field(default_factory=list)
    """How success will be measured."""

    kpis: list[str] = field(default_factory=list)
    """Key Performance Indicators."""

    # Release Planning
    mvp_scope: list[str] = field(default_factory=list)
    """What is included in the MVP."""

    future_scope: list[str] = field(default_factory=list)
    """What is planned for future releases."""

    # Competitive Analysis
    competitors: list[str] = field(default_factory=list)
    """Key competitors in the space."""

    differentiation: list[str] = field(default_factory=list)
    """What makes this product different."""

    # Timeline
    estimated_timeline: str = ""
    """Estimated timeline for delivery."""

    def to_dict(self) -> dict:
        """Convert to a JSON-serializable dictionary."""
        return {
            "project_title": self.project_title,
            "problem_statement": self.problem_statement,
            "project_vision": self.project_vision,
            "target_audience": list(self.target_audience),
            "user_personas": list(self.user_personas),
            "user_journeys": list(self.user_journeys),
            "features": list(self.features),
            "success_metrics": list(self.success_metrics),
            "kpis": list(self.kpis),
            "mvp_scope": list(self.mvp_scope),
            "future_scope": list(self.future_scope),
            "competitors": list(self.competitors),
            "differentiation": list(self.differentiation),
            "estimated_timeline": self.estimated_timeline,
        }

    def to_markdown(self) -> str:
        """Convert to a formatted Markdown document."""
        lines = []
        lines.append(f"# Product Requirements Document — {self.project_title}")
        lines.append("")

        if self.problem_statement:
            lines.append("## Problem Statement")
            lines.append("")
            lines.append(self.problem_statement)
            lines.append("")

        if self.project_vision:
            lines.append("## Project Vision")
            lines.append("")
            lines.append(self.project_vision)
            lines.append("")

        if self.target_audience:
            lines.append("## Target Audience")
            lines.append("")
            for item in self.target_audience:
                lines.append(f"- {item}")
            lines.append("")

        if self.user_personas:
            lines.append("## User Personas")
            lines.append("")
            for persona in self.user_personas:
                lines.append(f"- {persona}")
            lines.append("")

        if self.user_journeys:
            lines.append("## User Journeys")
            lines.append("")
            for journey in self.user_journeys:
                lines.append(f"- {journey}")
            lines.append("")

        if self.features:
            lines.append("## Features")
            lines.append("")
            for feature in self.features:
                lines.append(f"- {feature}")
            lines.append("")

        if self.success_metrics:
            lines.append("## Success Metrics")
            lines.append("")
            for metric in self.success_metrics:
                lines.append(f"- {metric}")
            lines.append("")

        if self.kpis:
            lines.append("## Key Performance Indicators")
            lines.append("")
            for kpi in self.kpis:
                lines.append(f"- {kpi}")
            lines.append("")

        if self.mvp_scope:
            lines.append("## MVP Scope")
            lines.append("")
            for item in self.mvp_scope:
                lines.append(f"- {item}")
            lines.append("")

        if self.future_scope:
            lines.append("## Future Scope")
            lines.append("")
            for item in self.future_scope:
                lines.append(f"- {item}")
            lines.append("")

        if self.competitors:
            lines.append("## Competitors")
            lines.append("")
            for competitor in self.competitors:
                lines.append(f"- {competitor}")
            lines.append("")

        if self.differentiation:
            lines.append("## Differentiation")
            lines.append("")
            for item in self.differentiation:
                lines.append(f"- {item}")
            lines.append("")

        if self.estimated_timeline:
            lines.append("## Estimated Timeline")
            lines.append("")
            lines.append(self.estimated_timeline)
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by AI Engineering Team — PRD Generator*")
        lines.append("")

        return "\n".join(lines)
