"""
Canonical Requirements domain model.

Represents a complete set of requirements for a project.
The Requirements Generator produces this model from an analyzed Idea.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Requirements:
    """
    A complete set of project requirements.

    Generated by the Requirements Generator stage from an Idea model.
    """

    # Overview
    project_title: str
    """Title of the project these requirements belong to."""

    project_summary: str
    """One-paragraph summary of the project."""

    # Functional Requirements
    functional_requirements: list[str] = field(default_factory=list)
    """What the system must do — prioritized features and capabilities."""

    # Non-Functional Requirements
    non_functional_requirements: list[str] = field(default_factory=list)
    """Quality attributes — performance, security, scalability, usability, etc."""

    # User Stories
    user_stories: list[str] = field(default_factory=list)
    """User stories in 'As a... I want... So that...' format."""

    # Acceptance Criteria
    acceptance_criteria: list[str] = field(default_factory=list)
    """Conditions that must be met for the project to be accepted."""

    # Priority
    must_have: list[str] = field(default_factory=list)
    """Critical features required for MVP."""

    should_have: list[str] = field(default_factory=list)
    """Important features that can wait if needed."""

    could_have: list[str] = field(default_factory=list)
    """Nice-to-have features for future iterations."""

    # Dependencies
    external_dependencies: list[str] = field(default_factory=list)
    """External systems, APIs, or services the project depends on."""

    # Scope
    in_scope: list[str] = field(default_factory=list)
    """What is explicitly included in this project."""

    out_of_scope: list[str] = field(default_factory=list)
    """What is explicitly excluded from this project."""

    def to_dict(self) -> dict:
        """Convert to a JSON-serializable dictionary."""
        return {
            "project_title": self.project_title,
            "project_summary": self.project_summary,
            "functional_requirements": list(self.functional_requirements),
            "non_functional_requirements": list(self.non_functional_requirements),
            "user_stories": list(self.user_stories),
            "acceptance_criteria": list(self.acceptance_criteria),
            "must_have": list(self.must_have),
            "should_have": list(self.should_have),
            "could_have": list(self.could_have),
            "external_dependencies": list(self.external_dependencies),
            "in_scope": list(self.in_scope),
            "out_of_scope": list(self.out_of_scope),
        }

    def to_markdown(self) -> str:
        """Convert to a formatted Markdown document."""
        lines = []
        lines.append(f"# Requirements — {self.project_title}")
        lines.append("")
        lines.append("## Project Summary")
        lines.append("")
        lines.append(self.project_summary)
        lines.append("")

        if self.functional_requirements:
            lines.append("## Functional Requirements")
            lines.append("")
            for req in self.functional_requirements:
                lines.append(f"- {req}")
            lines.append("")

        if self.non_functional_requirements:
            lines.append("## Non-Functional Requirements")
            lines.append("")
            for req in self.non_functional_requirements:
                lines.append(f"- {req}")
            lines.append("")

        if self.user_stories:
            lines.append("## User Stories")
            lines.append("")
            for story in self.user_stories:
                lines.append(f"- {story}")
            lines.append("")

        if self.acceptance_criteria:
            lines.append("## Acceptance Criteria")
            lines.append("")
            for criterion in self.acceptance_criteria:
                lines.append(f"- {criterion}")
            lines.append("")

        if self.must_have or self.should_have or self.could_have:
            lines.append("## Priority Breakdown")
            lines.append("")

            if self.must_have:
                lines.append("### Must Have (MVP)")
                lines.append("")
                for item in self.must_have:
                    lines.append(f"- {item}")
                lines.append("")

            if self.should_have:
                lines.append("### Should Have")
                lines.append("")
                for item in self.should_have:
                    lines.append(f"- {item}")
                lines.append("")

            if self.could_have:
                lines.append("### Could Have")
                lines.append("")
                for item in self.could_have:
                    lines.append(f"- {item}")
                lines.append("")

        if self.external_dependencies:
            lines.append("## External Dependencies")
            lines.append("")
            for dep in self.external_dependencies:
                lines.append(f"- {dep}")
            lines.append("")

        if self.in_scope:
            lines.append("## In Scope")
            lines.append("")
            for item in self.in_scope:
                lines.append(f"- {item}")
            lines.append("")

        if self.out_of_scope:
            lines.append("## Out of Scope")
            lines.append("")
            for item in self.out_of_scope:
                lines.append(f"- {item}")
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by AI Engineering Team — Requirements Generator*")
        lines.append("")

        return "\n".join(lines)
