"""
Canonical TaskPlan domain model.

Represents a comprehensive roadmap of epics, stories, and tasks.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Task:
    """A single actionable task."""

    title: str
    description: str
    priority: str  # High, Medium, Low
    dependencies: list[str] = field(default_factory=list)
    estimated_effort: str = ""  # e.g. "3 points", "1 day"
    acceptance_criteria: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "description": self.description,
            "priority": self.priority,
            "dependencies": list(self.dependencies),
            "estimated_effort": self.estimated_effort,
            "acceptance_criteria": list(self.acceptance_criteria),
        }


@dataclass(frozen=True)
class Story:
    """A user story containing multiple tasks."""

    title: str
    description: str
    priority: str
    tasks: list[Task] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "description": self.description,
            "priority": self.priority,
            "tasks": [t.to_dict() for t in self.tasks],
        }


@dataclass(frozen=True)
class Epic:
    """A large body of work (Epic) containing multiple user stories."""

    title: str
    description: str
    stories: list[Story] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "description": self.description,
            "stories": [s.to_dict() for s in self.stories],
        }


@dataclass(frozen=True)
class TaskPlan:
    """Canonical TaskPlan representation."""

    project_title: str
    epics: list[Epic] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Convert to a JSON-serializable dictionary."""
        return {
            "project_title": self.project_title,
            "epics": [e.to_dict() for e in self.epics],
        }

    def to_markdown(self) -> str:
        """Convert to a formatted Markdown document."""
        lines = []
        lines.append(f"# Project Roadmap & Implementation Plan — {self.project_title}")
        lines.append("")

        for epic in self.epics:
            lines.append(f"## Epic: {epic.title}")
            lines.append("")
            lines.append(epic.description)
            lines.append("")

            for story in epic.stories:
                lines.append(f"### Story: {story.title}")
                lines.append("")
                lines.append(f"**Priority**: {story.priority}")
                lines.append("")
                lines.append(story.description)
                lines.append("")

                if story.tasks:
                    lines.append("#### Tasks")
                    lines.append("")
                    for task in story.tasks:
                        lines.append(f"##### [ ] {task.title}")
                        lines.append("")
                        lines.append(task.description)
                        lines.append("")
                        lines.append(f"- **Priority**: {task.priority}")
                        lines.append(f"- **Estimate**: {task.estimated_effort}")
                        if task.dependencies:
                            lines.append(
                                f"- **Dependencies**: {', '.join(task.dependencies)}"
                            )
                        if task.acceptance_criteria:
                            lines.append("- **Acceptance Criteria**:")
                            for ac in task.acceptance_criteria:
                                lines.append(f"  - [ ] {ac}")
                        lines.append("")
            lines.append("---")

        lines.append("")
        lines.append("*Generated by AI Engineering Team — Task Planner*")
        lines.append("")

        return "\n".join(lines)
